<?php

namespace ovargas\fluentrules;

/**
 * CaptchaRuleBuilder configures validation rules for CAPTCHA fields.
 *
 * It directly maps to the Yii2 validator `yii\captcha\CaptchaValidator`, ensuring that
 * the user-entered value matches the code generated by the CAPTCHA action.
 *
 * @author Omar Vargas
 * @since 1.0.0
 */
class CaptchaRuleBuilder extends RuleBuilder
{
    /**
     * Initializes a new instance of the CAPTCHA validator.
     *
     * @param Attribute $attribute The attribute associated with the rule.
     */
    public function __construct(Attribute $attribute)
    {
        parent::__construct($attribute, 'captcha');
    }

    /**
     * Specifies the route (route ID) of the action responsible for rendering the CAPTCHA.
     * By default in Yii2 it is 'site/captcha'.
     *
     * @param string $action The route of the action (e.g. 'site/captcha').
     * @return $this
     */
    public function captchaAction(string $action): static
    {
        $this->_params['captchaAction'] = $action;
        return $this;
    }

    /**
     * Sets whether the validation of the entered code should be case-sensitive.
     * By default in Yii2 it is false.
     *
     * @param bool $caseSensitive Defaults to true when the method is invoked.
     * @return $this
     */
    public function caseSensitive(bool $caseSensitive = true): static
    {
        $this->_params['caseSensitive'] = $caseSensitive;
        return $this;
    }
}